bl_bibliotheque:
    resource: "@BlBibliothequeBundle/Controller/"
    type:     annotation
    prefix:   /

bl_bibliotheque_admin:
    path: /admin
    defaults: { _controller: BlBibliothequeBundle:Admin:index}

_admin_genre:
    resource: "@BlBibliothequeBundle/Controller/GenreController.php"
    type:     annotation
    prefix:   /admin

_admin_livre:
    resource: "@BlBibliothequeBundle/Controller/LivreController.php"
    type:     annotation
    prefix:   /admin




_security:
    resource: "@BlBibliothequeBundle/Controller/SecurityController.php"
    type:     annotation

# Cette route sera gérée automatiquement par symfony, il faut juste la déclarer
_security_login_check:
    pattern: /login_check

# Cette route sera gérée automatiquement par symfony, il faut juste la déclarer
_security_logout:
    pattern: /logout

_admin:
    resource: "@BlBibliothequeBundle/Controller/AdminController.php"
    type:     annotation

_genre:
    resource: "@BlBibliothequeBundle/Controller/GenreController.php"
    type:     annotation

_livre:
    resource: "@BlBibliothequeBundle/Controller/LivreController.php"
    type:     annotation

_default:
    resource: "@BlBibliothequeBundle/Controller/DefaultController.php"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"



fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

