bl_bibliotheque:
    resource: "@BlBibliothequeBundle/Controller/"
    type:     annotation
    prefix:   /

bl_bibliotheque_admin:
    path: /admin
    defaults: { _controller: BlBibliothequeBundle:Admin:index}

_admin_genre:
    resource: "@BlBibliothequeBundle/Controller/GenreController.php"
    type:     annotation
    prefix:   /admin

_admin_livre:
    resource: "@BlBibliothequeBundle/Controller/LivreController.php"
    type:     annotation
    prefix:   /admin




_security:
    resource: "@BlBibliothequeBundle/Controller/SecurityController.php"
    type:     annotation

# Cette route sera gérée automatiquement par symfony, il faut juste la déclarer
_security_login_check:
    pattern: /login_check

# Cette route sera gérée automatiquement par symfony, il faut juste la déclarer
_security_logout:
    pattern: /logout

_admin:
    resource: "@BlBibliothequeBundle/Controller/AdminController.php"
    type:     annotation

_genre:
    resource: "@BlBibliothequeBundle/Controller/GenreController.php"
    type:     annotation

_livre:
    resource: "@BlBibliothequeBundle/Controller/LivreController.php"
    type:     annotation

_default:
    resource: "@BlBibliothequeBundle/Controller/DefaultController.php"
    type:     annotation


