<?php

namespace Bl\BibliothequeBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * GenreRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GenreRepository extends EntityRepository
{
 public function fetchAllWithLivresCount()
    {
       /* Création de la requète avec le query builder */
        $queryBuilder = $this->_em->createQueryBuilder();
        $queryBuilder->select("g as genre, count(f) as nbConcernedLivres")
                     ->from("BlBibliothequeBundle:Genre", "g")
                     ->leftJoin("g.listeDesLivres", "f")
                     ->groupBy("g");
       /* On retourne les enregistrements, il s'agira d'un table multidimentionnel
        * Le premier paramètre "genre" contiendra notre entité genre
        * Le 2ème paramètre nbConcernedLivres contient le nombre de Livres du genre
        * On aurait pu tout simplement faire un findAll() en y mettant une jointure et compter
        * simplement le nombre de genre associés, mais cela chargerait les données des genres qui
        * nous sont ici inutiles.
        */
        return $queryBuilder->getQuery()->getResult();

    }
}
